<a href="https://colab.research.google.com/github/Deepak-Mewada/TensorFlowAdvancedTechniquesSpecialization_DeeplearningAI/blob/main/C1/W2/TF2C1W2L1_huber_loss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ungraded Lab: Huber Loss


In this lab, we'll walk through how to create custom loss functions. In particular, we'll code the [Huber Los](https://en.wikipedia.org/wiki/Huber_loss)s and use that in training the model.

# Import

In [2]:
import tensorflow as tf 
import numpy as np
from tensorflow import keras

# Prepare the data

Our dummy dataset is just a pair of arrays xs and ys defined by the relationship  𝑦=2𝑥−1
 . xs are the inputs while ys are the labels.

In [50]:
#inputs 
xs = np.array([10,2.0, 3.0,4.0,5.0,6.0,10,18,-10], dtype = float)

#labels
ys = np.array([1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 19.0, 35.0, -21], dtype= float)

# Training the model

Let's build a simple model and train using a built-in loss function like the mean_squared_error.

In [51]:
model_1 = tf.keras.Sequential([tf.keras.layers.Dense(units=1, input_shape = [1])])

model_1.compile(
    optimizer = 'sgd',
    loss = 'mean_squared_error')

model_1.fit(xs,ys, epochs=500, verbose = 0)

model_1.predict([10.0])

1/1 [==============================] - 0s 56ms/step


array([[16.145185]], dtype=float32)

## Custom Loss

 use a custom loss. We first define a function that accepts the ground truth labels (y_true) and model predictions (y_pred) as parameters. We then compute and return the loss value in the function definition.

In [52]:
def my_huber_loss(y_true, y_pred):
  threshold = 1
  error = y_true-y_pred
  is_small_a = tf.abs(error) <= threshold
  small_loss = tf.square(error) * 0.5
  large_loss = threshold * (tf.abs(error) - (threshold * 0.5))
  return tf.where(is_small_a , small_loss, large_loss)

In [53]:
my_huber_loss(xs,ys)

<tf.Tensor: shape=(9,), dtype=float64, numpy=array([ 8.5,  0.5,  1.5,  2.5,  3.5,  4.5,  8.5, 16.5, 10.5])>

Using the loss function is as simple as specifying the loss function in the loss argument of model.compile().

In [54]:
model_2 = tf.keras.Sequential([tf.keras.layers.Dense(units = 1, input_shape = [1] )])
model_2.compile(optimizer = 'sgd',loss = my_huber_loss)
model_2.fit(xs, ys, epochs=500, verbose = 0)

model_2.predict([10.0])

1/1 [==============================] - 0s 48ms/step


array([[18.840788]], dtype=float32)

Ya hu !!!!


# Custom loss parametrised


In [64]:
def my_huber_loss_parametrized(threshold=1):
  def my_huber_loss(y_true, y_pred):
    error = y_true-y_pred
    is_small_a = tf.abs(error) <= threshold
    loss_small = tf.square(error) * 0.5
    loss_large = threshold * (tf.abs(error) - 0.5 * threshold)
    return tf.where(is_small_a , loss_small , loss_large)
  return my_huber_loss  
  

In [65]:
model_3 = tf.keras.Sequential([tf.keras.layers.Dense(units =1 , input_shape = [1])])
model_3.compile(optimizer = 'sgd',
                loss = my_huber_loss_parametrized(threshold=0.5))
model_3.fit(xs,ys, epochs = 500, verbose = 0)

model_3.predict([10])

1/1 [==============================] - 0s 52ms/step


array([[18.955181]], dtype=float32)